<?php
/**
 * Category sidebar
 *
 * @var $block Sebwite\Sidebar\Block\Sidebar
 */
$categories = $block->getCategories();

// Loop through categories
foreach($categories as $category) {

    // Echo parent category
    echo '<h4><a href="' . $block->getCategoryUrl($category) . '" title="' . $category->getName() . '" class="' . ($block->isActive($category) ? 'is-active' : '') . '">' . $category->getName() . '</a></h4>';

    echo $block->getChildCategoryView($category);
}